name: Deploy to dev environment

on:
  push:
    branches:
      - dev
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy scripts on UAT
        uses: appleboy/ssh-action@v0.0.6
        with:
          script: |
            bash /var/www/shop-demo.dadventures.com/user-activity-log/scripts/deploy-dev.sh
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: ls

