name: Deploy to prod environment

on:
  push:
    branches:
      - master
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy scripts on UAT
        uses: appleboy/ssh-action@v0.0.6
        with:
          script: |
            bash /var/www/shop-demo.dadventures.com/user-activity-log/scripts/deploy-prod.sh
        env:
          HOST:  ${{ secrets.SSH_DEV_DEPLOYMENT_HOST }}
          USERNAME: ${{ secrets.SSH_DEV_DEPLOYMENT_USER }}
          PASSWORD: ${{ secrets.SSH_DEV_DEPLOYMENT_PASSWORD }}
